sudo: required

language: cpp

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - docker pull ubuntu:artful
  - docker run -it -d --name build user/build bash
  - docker exec build git clone https://github.com/Lord-Nazdar/CD4017
  - docker exec build sudo apt-get install gcc-avr binutils-avr avr-libc

script:
  - docker exec build cmake .
  - docker exec build make